shopflow:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'shopflow_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'shopflow_secret_2026') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'shopflow') }}"
      schema: staging
      threads: 4
      